fix(cid): enable reusable workflow to build nix images
Signed-off-by: Cameron Smith <cameron.ray.smith@gmail.com>

diff --git a/.github/workflows/cid.yaml b/.github/workflows/cid.yaml
--- a/.github/workflows/cid.yaml
+++ b/.github/workflows/cid.yaml
@@ -104,20 +104,25 @@ jobs:
               MODE="dev"
             fi
             CHECKOUT_REF="${{ github.event.pull_request.head.ref }}"
+            CHECKOUT_REV="${{ github.event.pull_request.head.sha }}"
           else
-            CHECKOUT_REF="${{ github.ref }}"
+            CHECKOUT_REF="${{ github.ref_name }}"
+            CHECKOUT_REV="${{ github.sha }}"
           fi
 
           echo "DEBUG=$DEBUG"
           echo "MODE=$MODE"
           echo "SKIP_CI=$SKIP_CI"
           echo "SKIP_TESTS=$SKIP_TESTS"
+          echo "CHECKOUT_REF=$CHECKOUT_REF"
+          echo "CHECKOUT_REV=$CHECKOUT_REV"
 
           echo "DEBUG=$DEBUG" >> $GITHUB_OUTPUT
           echo "MODE=$MODE" >> $GITHUB_OUTPUT
           echo "SKIP_CI=$SKIP_CI" >> $GITHUB_OUTPUT
           echo "SKIP_TESTS=$SKIP_TESTS" >> $GITHUB_OUTPUT
           echo "CHECKOUT_REF=$CHECKOUT_REF" >> $GITHUB_OUTPUT
+          echo "CHECKOUT_REV=$CHECKOUT_REV" >> $GITHUB_OUTPUT
 
   config-workflows:
     needs: [set-variables]
@@ -362,64 +367,78 @@ jobs:
       mode: ${{ needs.set-variables.outputs.mode }}
 
   build-nix-images:
-    runs-on: ubuntu-latest
     needs: [set-variables]
     if: ${{ needs.set-variables.outputs.skip_ci != 'true' && ( contains(github.event.pull_request.labels.*.name, 'build-images') || contains(github.event.pull_request.labels.*.name, 'execute-workflow') || (github.event_name == 'workflow_dispatch' && inputs.run_build_images) || (github.event_name == 'workflow_dispatch' && inputs.run_execute_workflow) ) }}
+    uses: ./.github/workflows/build-nix-images.yaml
     concurrency:
-      group: bni-${{ matrix.image }}-${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}-${{ needs.set-variables.outputs.mode }}
+      group: bni-${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref_name }}-${{ needs.set-variables.outputs.mode }}
       cancel-in-progress: true
-    permissions:
-      contents: read
-      packages: write
-    strategy:
-      matrix:
-        image:
-          [
-            "pyrovelocity",
-            "pyrovelocitydev",
-            "pyrovelocitycode",
-            "pyrovelocityjupyter",
-          ]
-    steps:
-      - name: Maximize build space
-        # uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c # ratchet:easimon/maximize-build-space@v10
-        uses: cameronraysmith/maximize-build-space@fdf0c06b18d92be98aa64cb68ae4ea4c9bc4794d # ratchet:cameronraysmith/maximize-build-space@print-usage
-        if: ${{ needs.set-variables.outputs.mode != 'dev' }}
-        with:
-          build-mount-path: /nix
-          build-mount-path-ownership: "root:root"
-          root-reserve-mb: 34816
-          swap-size-mb: 2048
-          remove-dotnet: "true"
-          remove-android: "true"
-          remove-codeql: "true"
-          remove-docker-images: "true"
+    with:
+      debug_enabled: ${{ needs.set-variables.outputs.debug }}
+      version: ""
+      images: '["pyrovelocity","pyrovelocitydev","pyrovelocitycode","pyrovelocityjupyter"]'
+      branch: ${{ needs.set-variables.outputs.checkout_ref }}
+      revision: ${{ needs.set-variables.outputs.checkout_rev }}
 
-      - name: Setup build environment
-        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
-        if: ${{ needs.set-variables.outputs.mode != 'dev' }}
-        with:
-          ref: ${{ needs.set-variables.outputs.checkout_ref }}
+  # build-nix-images:
+  #   runs-on: ubuntu-latest
+  #   needs: [set-variables]
+  #   if: ${{ needs.set-variables.outputs.skip_ci != 'true' && ( contains(github.event.pull_request.labels.*.name, 'build-images') || contains(github.event.pull_request.labels.*.name, 'execute-workflow') || (github.event_name == 'workflow_dispatch' && inputs.run_build_images) || (github.event_name == 'workflow_dispatch' && inputs.run_execute_workflow) ) }}
+  #   concurrency:
+  #     group: bni-${{ matrix.image }}-${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.event.pull_request.number || github.ref }}-${{ needs.set-variables.outputs.mode }}
+  #     cancel-in-progress: true
+  #   permissions:
+  #     contents: read
+  #     packages: write
+  #   strategy:
+  #     matrix:
+  #       image:
+  #         [
+  #           "pyrovelocity",
+  #           "pyrovelocitydev",
+  #           "pyrovelocitycode",
+  #           "pyrovelocityjupyter",
+  #         ]
+  #   steps:
+  #     - name: Maximize build space
+  #       # uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c # ratchet:easimon/maximize-build-space@v10
+  #       uses: cameronraysmith/maximize-build-space@fdf0c06b18d92be98aa64cb68ae4ea4c9bc4794d # ratchet:cameronraysmith/maximize-build-space@print-usage
+  #       if: ${{ needs.set-variables.outputs.mode != 'dev' }}
+  #       with:
+  #         build-mount-path: /nix
+  #         build-mount-path-ownership: "root:root"
+  #         root-reserve-mb: 34816
+  #         swap-size-mb: 2048
+  #         remove-dotnet: "true"
+  #         remove-android: "true"
+  #         remove-codeql: "true"
+  #         remove-docker-images: "true"
 
-      - name: Build ${{ matrix.image }} image
-        uses: ./.github/actions/build_nix_image
-        if: ${{ needs.set-variables.outputs.mode != 'dev' }}
-        with:
-          triggerEventName: ${{ github.event_name }}
-          imageName: "${{ matrix.image }}"
-          nixCommand: "nix run .#${{ matrix.image }}Manifest --impure --accept-flake-config --show-trace"
-          releaseVersion: ""
-          gcpProjectId: ${{ secrets.GCP_PROJECT_ID }}
-          encodedGARCredentials: ${{ secrets.ENCODED_GAR_SA_CREDS }}
-          artifactRegistryPassword: ${{ secrets.ARTIFACT_REGISTRY_PASSWORD }}
-          nixSubstituterName: ${{ vars.NIX_SUBSTITUTER }}
-          # nixSubstituterName: ${{ vars.S3_NIX_SUBSTITUTER }}
-          nixPrivateKey: ${{ secrets.NIX_PRIVATE_KEY }}
-          gacd: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}
-          gcsHmacAccessID: ${{ secrets.GCS_HMAC_ACCESS_ID }}
-          gcsHmacSecretAccessKey: ${{ secrets.GCS_HMAC_SECRET_ACCESS_KEY }}
-          cachixCacheName: ${{ vars.CACHIX_CACHE_NAME }}
-          cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
+  #     - name: Setup build environment
+  #       uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
+  #       if: ${{ needs.set-variables.outputs.mode != 'dev' }}
+  #       with:
+  #         ref: ${{ needs.set-variables.outputs.checkout_ref }}
+
+  #     - name: Build ${{ matrix.image }} image
+  #       uses: ./.github/actions/build_nix_image
+  #       if: ${{ needs.set-variables.outputs.mode != 'dev' }}
+  #       with:
+  #         triggerEventName: ${{ github.event_name }}
+  #         imageName: "${{ matrix.image }}"
+  #         nixCommand: "nix run .#${{ matrix.image }}Manifest --impure --accept-flake-config --show-trace"
+  #         releaseVersion: ""
+  #         gcpProjectId: ${{ secrets.GCP_PROJECT_ID }}
+  #         encodedGARCredentials: ${{ secrets.ENCODED_GAR_SA_CREDS }}
+  #         artifactRegistryPassword: ${{ secrets.ARTIFACT_REGISTRY_PASSWORD }}
+  #         nixSubstituterName: ${{ vars.NIX_SUBSTITUTER }}
+  #         # nixSubstituterName: ${{ vars.S3_NIX_SUBSTITUTER }}
+  #         nixPrivateKey: ${{ secrets.NIX_PRIVATE_KEY }}
+  #         gacd: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}
+  #         gcsHmacAccessID: ${{ secrets.GCS_HMAC_ACCESS_ID }}
+  #         gcsHmacSecretAccessKey: ${{ secrets.GCS_HMAC_SECRET_ACCESS_KEY }}
+  #         cachixCacheName: ${{ vars.CACHIX_CACHE_NAME }}
+  #         cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
 
   execute-workflow:
     # needs: [config-workflows, build-nix-images, set-variables]
@@ -541,61 +560,75 @@ jobs:
           # tag: v0.2.0-beta.10
 
   publish-release-images:
-    runs-on: ubuntu-latest
     needs: [set-variables, release]
     if: ${{ needs.release.outputs.released == 'true' }}
-    strategy:
-      fail-fast: false
-      matrix:
-        image:
-          [
-            "pyrovelocity",
-            "pyrovelocitydev",
-            "pyrovelocitycode",
-            "pyrovelocityjupyter",
-          ]
+    uses: ./.github/workflows/build-nix-images.yaml
     concurrency:
-      group: pri-${{ matrix.image }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
+      group: pri-${{ github.workflow }}-${{ github.ref_name }}-${{ github.sha }}
       cancel-in-progress: true
-    permissions:
-      contents: read
-      packages: write
-    # environment:
-    #   name: release
-    #   url: ${{ matrix.url }}
-    steps:
-      - name: maximize build space
-        # uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c # ratchet:easimon/maximize-build-space@v10
-        uses: cameronraysmith/maximize-build-space@fdf0c06b18d92be98aa64cb68ae4ea4c9bc4794d # ratchet:cameronraysmith/maximize-build-space@print-usage
-        with:
-          build-mount-path: /nix
-          build-mount-path-ownership: "root:root"
-          root-reserve-mb: 34816
-          swap-size-mb: 2048
-          remove-dotnet: "true"
-          remove-android: "true"
-          remove-codeql: "true"
-          remove-docker-images: "true"
-      - name: Setup build environment
-        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
-        with:
-          ref: ${{ needs.release.outputs.git-tag }}
-      - name: Build ${{ matrix.image }} image
-        uses: ./.github/actions/build_nix_image
-        if: ${{ needs.set-variables.outputs.mode != 'dev' }}
-        with:
-          triggerEventName: ${{ github.event_name }}
-          imageName: "${{ matrix.image }}"
-          nixCommand: "nix run .#${{ matrix.image }}Manifest --impure --accept-flake-config --show-trace"
-          releaseVersion: ${{ needs.release.outputs.version }}
-          gcpProjectId: ${{ secrets.GCP_PROJECT_ID }}
-          encodedGARCredentials: ${{ secrets.ENCODED_GAR_SA_CREDS }}
-          artifactRegistryPassword: ${{ secrets.ARTIFACT_REGISTRY_PASSWORD }}
-          nixSubstituterName: ${{ vars.NIX_SUBSTITUTER }}
-          nixPrivateKey: ${{ secrets.NIX_PRIVATE_KEY }}
-          gacd: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}
-          cachixCacheName: ${{ vars.CACHIX_CACHE_NAME }}
-          cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
+    with:
+      debug_enabled: ${{ needs.set-variables.outputs.debug }}
+      version: ${{ needs.release.outputs.version }}
+      images: '["pyrovelocity","pyrovelocitydev","pyrovelocitycode","pyrovelocityjupyter"]'
+      branch: ${{ needs.set-variables.outputs.checkout_ref }}
+      revision: ${{ needs.release.outputs.git-head }}
+
+  # publish-release-images:
+  #   runs-on: ubuntu-latest
+  #   needs: [set-variables, release]
+  #   if: ${{ needs.release.outputs.released == 'true' }}
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       image:
+  #         [
+  #           "pyrovelocity",
+  #           "pyrovelocitydev",
+  #           "pyrovelocitycode",
+  #           "pyrovelocityjupyter",
+  #         ]
+  #   concurrency:
+  #     group: pri-${{ matrix.image }}-${{ github.workflow }}-${{ github.ref }}-${{ github.sha }}
+  #     cancel-in-progress: true
+  #   permissions:
+  #     contents: read
+  #     packages: write
+  #   # environment:
+  #   #   name: release
+  #   #   url: ${{ matrix.url }}
+  #   steps:
+  #     - name: maximize build space
+  #       # uses: easimon/maximize-build-space@fc881a613ad2a34aca9c9624518214ebc21dfc0c # ratchet:easimon/maximize-build-space@v10
+  #       uses: cameronraysmith/maximize-build-space@fdf0c06b18d92be98aa64cb68ae4ea4c9bc4794d # ratchet:cameronraysmith/maximize-build-space@print-usage
+  #       with:
+  #         build-mount-path: /nix
+  #         build-mount-path-ownership: "root:root"
+  #         root-reserve-mb: 34816
+  #         swap-size-mb: 2048
+  #         remove-dotnet: "true"
+  #         remove-android: "true"
+  #         remove-codeql: "true"
+  #         remove-docker-images: "true"
+  #     - name: Setup build environment
+  #       uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # ratchet:actions/checkout@v4
+  #       with:
+  #         ref: ${{ needs.release.outputs.git-tag }}
+  #     - name: Build ${{ matrix.image }} image
+  #       uses: ./.github/actions/build_nix_image
+  #       if: ${{ needs.set-variables.outputs.mode != 'dev' }}
+  #       with:
+  #         triggerEventName: ${{ github.event_name }}
+  #         imageName: "${{ matrix.image }}"
+  #         nixCommand: "nix run .#${{ matrix.image }}Manifest --impure --accept-flake-config --show-trace"
+  #         releaseVersion: ${{ needs.release.outputs.version }}
+  #         gcpProjectId: ${{ secrets.GCP_PROJECT_ID }}
+  #         encodedGARCredentials: ${{ secrets.ENCODED_GAR_SA_CREDS }}
+  #         artifactRegistryPassword: ${{ secrets.ARTIFACT_REGISTRY_PASSWORD }}
+  #         nixSubstituterName: ${{ vars.NIX_SUBSTITUTER }}
+  #         nixPrivateKey: ${{ secrets.NIX_PRIVATE_KEY }}
+  #         gacd: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_DATA }}
+  #         cachixCacheName: ${{ vars.CACHIX_CACHE_NAME }}
+  #         cachixAuthToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
 
   publish-pypi:
     runs-on: ubuntu-latest
